### PR TITLE
own the writer in the encoder and rustfmt all on the file

### PR DESCRIPTION
**Pull request by vadixidav**
Re-added the comment in a commit --amend.

### CODE REVIEW

**Comment by Kagami** [comment]
Please create separate commit for formating fixes.

>/// Error while parsing the file/frame header.

And don't move that line :)

**Comment by Kagami** [comment]
Err, separate PR.

**Comment by vadixidav** [comment]
The doc comment wont work if its separated I think.

On Dec 10, 2016 8:22 PM, "Kagami Hiiragi" <notifications@github.com> wrote:

Err, separate PR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PistonDevelopers/y4m/pull/8#issuecomment-266254201>,
or mute
the thread

**Comment by Kagami** [comment]
1. Get fresh clone of repo.
2. Make writer owning changes, commit, send PR.
3. (Optional) Apply rustfmt, commit, create another PR for that.

Also, I'm not sure why the example still works. It passes `&mut outfh` instead of `outfh` but compiles ok. I will check that later.

**Comment by vadixidav** [comment]
I don't have the code without the formatting changes so I'll just pass for
now.

**Pull request closed without merging**
