### PR TITLE
Add cargo fmt to travis build config

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by JohnTitor** [comment]
I don't think we should check formatting on all builds, just stable is enough.

**Comment by JohnTitor** [comment]
@HeroicKatora btw, could you delete CircleCI workflows from this repo? I think we don't use it here anymore but it causes failure notifications :P

**Comment by 197g** [comment]
I've deleted the webhook at least. I'm not completely sure if that was all, but I can't seem to authorized myself to manage the `image-rs` repositores with CircleCI either. Ping me again if it is still an issue.

**Comment by Atul9** [comment]
@JohnTitor done, I have updated the PR, please check.

**Review by JohnTitor — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
